import { ApiProperty } from '@nestjs/swagger';

export class UpdateOrderResponseDto {
  @ApiProperty({ description: 'The unique order ID generated by TopDawg', example: '15533' })
  order_id: string;

  @ApiProperty({ description: 'Current processing status of the Order', example: '1' })
  status: string;
}
