import { ApiProperty } from '@nestjs/swagger';

export class CreateOrderResponseDto {
  @ApiProperty({ description: 'The unique order ID generated by TopDawg', example: '15533' })
  order_id: string;

  @ApiProperty({ description: 'Processing status of the Order (Status 1 is default on creation)', example: '1' })
  status: string;
}
